# Automatycznie wygenerowany + lekko poprawiony
name: Publish Docker Container

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Test
        run: dotnet test --no-restore -c Release
        env:
          JWT_SECRET_KEY: TestSecretKeyThatIsAtLeast32CharactersLong!
          JWT_ISSUER: SampleProject.API.Test
          JWT_AUDIENCE: SampleProject.Users.Test
          JWT_EXPIRATION_MINUTES: 60
          JWT_REFRESH_TOKEN_EXPIRATION_DAYS: 7
          JWT_USE_COOKIES: true
          JWT_ACCESS_TOKEN_COOKIE_NAME: auth_session
          JWT_REFRESH_TOKEN_COOKIE_NAME: auth_refresh
          JWT_COOKIE_DOMAIN: 
          JWT_COOKIE_PATH: /
          JWT_SECURE_COOKIES: false
          JWT_SAME_SITE_MODE: Lax

      - name: Publish
        run: dotnet publish SampleProject/SampleProject.csproj -c Release -o publish

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/api:latest
            ghcr.io/${{ github.repository }}/api:${{ github.ref_name }}
          build-args: |
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            JWT_ISSUER=${{ secrets.JWT_ISSUER }}
            JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}
            JWT_EXPIRATION_MINUTES=${{ secrets.JWT_EXPIRATION_MINUTES }}
            JWT_REFRESH_TOKEN_EXPIRATION_DAYS=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION_DAYS }}
            JWT_USE_COOKIES=${{ secrets.JWT_USE_COOKIES }}
            JWT_ACCESS_TOKEN_COOKIE_NAME=${{ secrets.JWT_ACCESS_TOKEN_COOKIE_NAME }}
            JWT_REFRESH_TOKEN_COOKIE_NAME=${{ secrets.JWT_REFRESH_TOKEN_COOKIE_NAME }}
            JWT_COOKIE_DOMAIN=${{ secrets.JWT_COOKIE_DOMAIN }}
            JWT_COOKIE_PATH=${{ secrets.JWT_COOKIE_PATH }}
            JWT_SECURE_COOKIES=${{ secrets.JWT_SECURE_COOKIES }}
            JWT_SAME_SITE_MODE=${{ secrets.JWT_SAME_SITE_MODE }}
